package com.lvsazf.mapper;

import com.lvsazf.model.Person;
import java.util.List;

public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa_opperson
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa_opperson
     *
     * @mbggenerated
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa_opperson
     *
     * @mbggenerated
     */
    Person selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa_opperson
     *
     * @mbggenerated
     */
    List<Person> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sa_opperson
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Person record);
}