package com.lvsazf.model;

import java.util.Date;

public class Person {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sID
     *
     * @mbggenerated
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sName
     *
     * @mbggenerated
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sCode
     *
     * @mbggenerated
     */
    private String scode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sIDCard
     *
     * @mbggenerated
     */
    private String sidcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sNumb
     *
     * @mbggenerated
     */
    private Integer snumb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sLoginName
     *
     * @mbggenerated
     */
    private String sloginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sPassword
     *
     * @mbggenerated
     */
    private String spassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sPasswordTimeLimit
     *
     * @mbggenerated
     */
    private Integer spasswordtimelimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sPasswordModifyTime
     *
     * @mbggenerated
     */
    private Date spasswordmodifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sMainOrgID
     *
     * @mbggenerated
     */
    private String smainorgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sSafeLevelID
     *
     * @mbggenerated
     */
    private String ssafelevelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sSequence
     *
     * @mbggenerated
     */
    private Integer ssequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sValidState
     *
     * @mbggenerated
     */
    private Integer svalidstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sDescription
     *
     * @mbggenerated
     */
    private String sdescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sPhotoLastModified
     *
     * @mbggenerated
     */
    private Date sphotolastmodified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sSex
     *
     * @mbggenerated
     */
    private String ssex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sBirthday
     *
     * @mbggenerated
     */
    private Date sbirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sJoinDate
     *
     * @mbggenerated
     */
    private Date sjoindate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sHomePlace
     *
     * @mbggenerated
     */
    private String shomeplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sCountry
     *
     * @mbggenerated
     */
    private String scountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sProvince
     *
     * @mbggenerated
     */
    private String sprovince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sCity
     *
     * @mbggenerated
     */
    private String scity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sDegree
     *
     * @mbggenerated
     */
    private String sdegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sGraduateSchool
     *
     * @mbggenerated
     */
    private String sgraduateschool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sSpeciality
     *
     * @mbggenerated
     */
    private String sspeciality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sSchoolLength
     *
     * @mbggenerated
     */
    private String sschoollength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sTitle
     *
     * @mbggenerated
     */
    private String stitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sMarriage
     *
     * @mbggenerated
     */
    private String smarriage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sCardNO
     *
     * @mbggenerated
     */
    private String scardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sCardKind
     *
     * @mbggenerated
     */
    private String scardkind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sFamilyAddress
     *
     * @mbggenerated
     */
    private String sfamilyaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sZip
     *
     * @mbggenerated
     */
    private String szip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sMsn
     *
     * @mbggenerated
     */
    private String smsn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sQQ
     *
     * @mbggenerated
     */
    private String sqq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sMail
     *
     * @mbggenerated
     */
    private String smail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sMobilePhone
     *
     * @mbggenerated
     */
    private String smobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sFamilyPhone
     *
     * @mbggenerated
     */
    private String sfamilyphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sOfficePhone
     *
     * @mbggenerated
     */
    private String sofficephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sEnglishName
     *
     * @mbggenerated
     */
    private String senglishname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sAge
     *
     * @mbggenerated
     */
    private Integer sage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sClassification
     *
     * @mbggenerated
     */
    private String sclassification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sState
     *
     * @mbggenerated
     */
    private String sstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sWorkLife
     *
     * @mbggenerated
     */
    private Integer sworklife;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sLearnExperience
     *
     * @mbggenerated
     */
    private String slearnexperience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sWorkExperience
     *
     * @mbggenerated
     */
    private String sworkexperience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sTrainExperience
     *
     * @mbggenerated
     */
    private String strainexperience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sCertificate
     *
     * @mbggenerated
     */
    private String scertificate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sSafeLevelName
     *
     * @mbggenerated
     */
    private String ssafelevelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sSexNo
     *
     * @mbggenerated
     */
    private String ssexno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sStateNO
     *
     * @mbggenerated
     */
    private String sstateno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.sPhoto
     *
     * @mbggenerated
     */
    private byte[] sphoto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sID
     *
     * @return the value of sa_opperson.sID
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sID
     *
     * @param sid the value for sa_opperson.sID
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sName
     *
     * @return the value of sa_opperson.sName
     *
     * @mbggenerated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sName
     *
     * @param sname the value for sa_opperson.sName
     *
     * @mbggenerated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sCode
     *
     * @return the value of sa_opperson.sCode
     *
     * @mbggenerated
     */
    public String getScode() {
        return scode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sCode
     *
     * @param scode the value for sa_opperson.sCode
     *
     * @mbggenerated
     */
    public void setScode(String scode) {
        this.scode = scode == null ? null : scode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sIDCard
     *
     * @return the value of sa_opperson.sIDCard
     *
     * @mbggenerated
     */
    public String getSidcard() {
        return sidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sIDCard
     *
     * @param sidcard the value for sa_opperson.sIDCard
     *
     * @mbggenerated
     */
    public void setSidcard(String sidcard) {
        this.sidcard = sidcard == null ? null : sidcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sNumb
     *
     * @return the value of sa_opperson.sNumb
     *
     * @mbggenerated
     */
    public Integer getSnumb() {
        return snumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sNumb
     *
     * @param snumb the value for sa_opperson.sNumb
     *
     * @mbggenerated
     */
    public void setSnumb(Integer snumb) {
        this.snumb = snumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sLoginName
     *
     * @return the value of sa_opperson.sLoginName
     *
     * @mbggenerated
     */
    public String getSloginname() {
        return sloginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sLoginName
     *
     * @param sloginname the value for sa_opperson.sLoginName
     *
     * @mbggenerated
     */
    public void setSloginname(String sloginname) {
        this.sloginname = sloginname == null ? null : sloginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sPassword
     *
     * @return the value of sa_opperson.sPassword
     *
     * @mbggenerated
     */
    public String getSpassword() {
        return spassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sPassword
     *
     * @param spassword the value for sa_opperson.sPassword
     *
     * @mbggenerated
     */
    public void setSpassword(String spassword) {
        this.spassword = spassword == null ? null : spassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sPasswordTimeLimit
     *
     * @return the value of sa_opperson.sPasswordTimeLimit
     *
     * @mbggenerated
     */
    public Integer getSpasswordtimelimit() {
        return spasswordtimelimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sPasswordTimeLimit
     *
     * @param spasswordtimelimit the value for sa_opperson.sPasswordTimeLimit
     *
     * @mbggenerated
     */
    public void setSpasswordtimelimit(Integer spasswordtimelimit) {
        this.spasswordtimelimit = spasswordtimelimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sPasswordModifyTime
     *
     * @return the value of sa_opperson.sPasswordModifyTime
     *
     * @mbggenerated
     */
    public Date getSpasswordmodifytime() {
        return spasswordmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sPasswordModifyTime
     *
     * @param spasswordmodifytime the value for sa_opperson.sPasswordModifyTime
     *
     * @mbggenerated
     */
    public void setSpasswordmodifytime(Date spasswordmodifytime) {
        this.spasswordmodifytime = spasswordmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sMainOrgID
     *
     * @return the value of sa_opperson.sMainOrgID
     *
     * @mbggenerated
     */
    public String getSmainorgid() {
        return smainorgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sMainOrgID
     *
     * @param smainorgid the value for sa_opperson.sMainOrgID
     *
     * @mbggenerated
     */
    public void setSmainorgid(String smainorgid) {
        this.smainorgid = smainorgid == null ? null : smainorgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sSafeLevelID
     *
     * @return the value of sa_opperson.sSafeLevelID
     *
     * @mbggenerated
     */
    public String getSsafelevelid() {
        return ssafelevelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sSafeLevelID
     *
     * @param ssafelevelid the value for sa_opperson.sSafeLevelID
     *
     * @mbggenerated
     */
    public void setSsafelevelid(String ssafelevelid) {
        this.ssafelevelid = ssafelevelid == null ? null : ssafelevelid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sSequence
     *
     * @return the value of sa_opperson.sSequence
     *
     * @mbggenerated
     */
    public Integer getSsequence() {
        return ssequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sSequence
     *
     * @param ssequence the value for sa_opperson.sSequence
     *
     * @mbggenerated
     */
    public void setSsequence(Integer ssequence) {
        this.ssequence = ssequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sValidState
     *
     * @return the value of sa_opperson.sValidState
     *
     * @mbggenerated
     */
    public Integer getSvalidstate() {
        return svalidstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sValidState
     *
     * @param svalidstate the value for sa_opperson.sValidState
     *
     * @mbggenerated
     */
    public void setSvalidstate(Integer svalidstate) {
        this.svalidstate = svalidstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sDescription
     *
     * @return the value of sa_opperson.sDescription
     *
     * @mbggenerated
     */
    public String getSdescription() {
        return sdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sDescription
     *
     * @param sdescription the value for sa_opperson.sDescription
     *
     * @mbggenerated
     */
    public void setSdescription(String sdescription) {
        this.sdescription = sdescription == null ? null : sdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sPhotoLastModified
     *
     * @return the value of sa_opperson.sPhotoLastModified
     *
     * @mbggenerated
     */
    public Date getSphotolastmodified() {
        return sphotolastmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sPhotoLastModified
     *
     * @param sphotolastmodified the value for sa_opperson.sPhotoLastModified
     *
     * @mbggenerated
     */
    public void setSphotolastmodified(Date sphotolastmodified) {
        this.sphotolastmodified = sphotolastmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sSex
     *
     * @return the value of sa_opperson.sSex
     *
     * @mbggenerated
     */
    public String getSsex() {
        return ssex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sSex
     *
     * @param ssex the value for sa_opperson.sSex
     *
     * @mbggenerated
     */
    public void setSsex(String ssex) {
        this.ssex = ssex == null ? null : ssex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sBirthday
     *
     * @return the value of sa_opperson.sBirthday
     *
     * @mbggenerated
     */
    public Date getSbirthday() {
        return sbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sBirthday
     *
     * @param sbirthday the value for sa_opperson.sBirthday
     *
     * @mbggenerated
     */
    public void setSbirthday(Date sbirthday) {
        this.sbirthday = sbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sJoinDate
     *
     * @return the value of sa_opperson.sJoinDate
     *
     * @mbggenerated
     */
    public Date getSjoindate() {
        return sjoindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sJoinDate
     *
     * @param sjoindate the value for sa_opperson.sJoinDate
     *
     * @mbggenerated
     */
    public void setSjoindate(Date sjoindate) {
        this.sjoindate = sjoindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sHomePlace
     *
     * @return the value of sa_opperson.sHomePlace
     *
     * @mbggenerated
     */
    public String getShomeplace() {
        return shomeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sHomePlace
     *
     * @param shomeplace the value for sa_opperson.sHomePlace
     *
     * @mbggenerated
     */
    public void setShomeplace(String shomeplace) {
        this.shomeplace = shomeplace == null ? null : shomeplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sCountry
     *
     * @return the value of sa_opperson.sCountry
     *
     * @mbggenerated
     */
    public String getScountry() {
        return scountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sCountry
     *
     * @param scountry the value for sa_opperson.sCountry
     *
     * @mbggenerated
     */
    public void setScountry(String scountry) {
        this.scountry = scountry == null ? null : scountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sProvince
     *
     * @return the value of sa_opperson.sProvince
     *
     * @mbggenerated
     */
    public String getSprovince() {
        return sprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sProvince
     *
     * @param sprovince the value for sa_opperson.sProvince
     *
     * @mbggenerated
     */
    public void setSprovince(String sprovince) {
        this.sprovince = sprovince == null ? null : sprovince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sCity
     *
     * @return the value of sa_opperson.sCity
     *
     * @mbggenerated
     */
    public String getScity() {
        return scity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sCity
     *
     * @param scity the value for sa_opperson.sCity
     *
     * @mbggenerated
     */
    public void setScity(String scity) {
        this.scity = scity == null ? null : scity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sDegree
     *
     * @return the value of sa_opperson.sDegree
     *
     * @mbggenerated
     */
    public String getSdegree() {
        return sdegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sDegree
     *
     * @param sdegree the value for sa_opperson.sDegree
     *
     * @mbggenerated
     */
    public void setSdegree(String sdegree) {
        this.sdegree = sdegree == null ? null : sdegree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sGraduateSchool
     *
     * @return the value of sa_opperson.sGraduateSchool
     *
     * @mbggenerated
     */
    public String getSgraduateschool() {
        return sgraduateschool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sGraduateSchool
     *
     * @param sgraduateschool the value for sa_opperson.sGraduateSchool
     *
     * @mbggenerated
     */
    public void setSgraduateschool(String sgraduateschool) {
        this.sgraduateschool = sgraduateschool == null ? null : sgraduateschool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sSpeciality
     *
     * @return the value of sa_opperson.sSpeciality
     *
     * @mbggenerated
     */
    public String getSspeciality() {
        return sspeciality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sSpeciality
     *
     * @param sspeciality the value for sa_opperson.sSpeciality
     *
     * @mbggenerated
     */
    public void setSspeciality(String sspeciality) {
        this.sspeciality = sspeciality == null ? null : sspeciality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sSchoolLength
     *
     * @return the value of sa_opperson.sSchoolLength
     *
     * @mbggenerated
     */
    public String getSschoollength() {
        return sschoollength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sSchoolLength
     *
     * @param sschoollength the value for sa_opperson.sSchoolLength
     *
     * @mbggenerated
     */
    public void setSschoollength(String sschoollength) {
        this.sschoollength = sschoollength == null ? null : sschoollength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sTitle
     *
     * @return the value of sa_opperson.sTitle
     *
     * @mbggenerated
     */
    public String getStitle() {
        return stitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sTitle
     *
     * @param stitle the value for sa_opperson.sTitle
     *
     * @mbggenerated
     */
    public void setStitle(String stitle) {
        this.stitle = stitle == null ? null : stitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sMarriage
     *
     * @return the value of sa_opperson.sMarriage
     *
     * @mbggenerated
     */
    public String getSmarriage() {
        return smarriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sMarriage
     *
     * @param smarriage the value for sa_opperson.sMarriage
     *
     * @mbggenerated
     */
    public void setSmarriage(String smarriage) {
        this.smarriage = smarriage == null ? null : smarriage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sCardNO
     *
     * @return the value of sa_opperson.sCardNO
     *
     * @mbggenerated
     */
    public String getScardno() {
        return scardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sCardNO
     *
     * @param scardno the value for sa_opperson.sCardNO
     *
     * @mbggenerated
     */
    public void setScardno(String scardno) {
        this.scardno = scardno == null ? null : scardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sCardKind
     *
     * @return the value of sa_opperson.sCardKind
     *
     * @mbggenerated
     */
    public String getScardkind() {
        return scardkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sCardKind
     *
     * @param scardkind the value for sa_opperson.sCardKind
     *
     * @mbggenerated
     */
    public void setScardkind(String scardkind) {
        this.scardkind = scardkind == null ? null : scardkind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sFamilyAddress
     *
     * @return the value of sa_opperson.sFamilyAddress
     *
     * @mbggenerated
     */
    public String getSfamilyaddress() {
        return sfamilyaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sFamilyAddress
     *
     * @param sfamilyaddress the value for sa_opperson.sFamilyAddress
     *
     * @mbggenerated
     */
    public void setSfamilyaddress(String sfamilyaddress) {
        this.sfamilyaddress = sfamilyaddress == null ? null : sfamilyaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sZip
     *
     * @return the value of sa_opperson.sZip
     *
     * @mbggenerated
     */
    public String getSzip() {
        return szip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sZip
     *
     * @param szip the value for sa_opperson.sZip
     *
     * @mbggenerated
     */
    public void setSzip(String szip) {
        this.szip = szip == null ? null : szip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sMsn
     *
     * @return the value of sa_opperson.sMsn
     *
     * @mbggenerated
     */
    public String getSmsn() {
        return smsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sMsn
     *
     * @param smsn the value for sa_opperson.sMsn
     *
     * @mbggenerated
     */
    public void setSmsn(String smsn) {
        this.smsn = smsn == null ? null : smsn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sQQ
     *
     * @return the value of sa_opperson.sQQ
     *
     * @mbggenerated
     */
    public String getSqq() {
        return sqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sQQ
     *
     * @param sqq the value for sa_opperson.sQQ
     *
     * @mbggenerated
     */
    public void setSqq(String sqq) {
        this.sqq = sqq == null ? null : sqq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sMail
     *
     * @return the value of sa_opperson.sMail
     *
     * @mbggenerated
     */
    public String getSmail() {
        return smail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sMail
     *
     * @param smail the value for sa_opperson.sMail
     *
     * @mbggenerated
     */
    public void setSmail(String smail) {
        this.smail = smail == null ? null : smail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sMobilePhone
     *
     * @return the value of sa_opperson.sMobilePhone
     *
     * @mbggenerated
     */
    public String getSmobilephone() {
        return smobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sMobilePhone
     *
     * @param smobilephone the value for sa_opperson.sMobilePhone
     *
     * @mbggenerated
     */
    public void setSmobilephone(String smobilephone) {
        this.smobilephone = smobilephone == null ? null : smobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sFamilyPhone
     *
     * @return the value of sa_opperson.sFamilyPhone
     *
     * @mbggenerated
     */
    public String getSfamilyphone() {
        return sfamilyphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sFamilyPhone
     *
     * @param sfamilyphone the value for sa_opperson.sFamilyPhone
     *
     * @mbggenerated
     */
    public void setSfamilyphone(String sfamilyphone) {
        this.sfamilyphone = sfamilyphone == null ? null : sfamilyphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sOfficePhone
     *
     * @return the value of sa_opperson.sOfficePhone
     *
     * @mbggenerated
     */
    public String getSofficephone() {
        return sofficephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sOfficePhone
     *
     * @param sofficephone the value for sa_opperson.sOfficePhone
     *
     * @mbggenerated
     */
    public void setSofficephone(String sofficephone) {
        this.sofficephone = sofficephone == null ? null : sofficephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sEnglishName
     *
     * @return the value of sa_opperson.sEnglishName
     *
     * @mbggenerated
     */
    public String getSenglishname() {
        return senglishname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sEnglishName
     *
     * @param senglishname the value for sa_opperson.sEnglishName
     *
     * @mbggenerated
     */
    public void setSenglishname(String senglishname) {
        this.senglishname = senglishname == null ? null : senglishname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.version
     *
     * @return the value of sa_opperson.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.version
     *
     * @param version the value for sa_opperson.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sAge
     *
     * @return the value of sa_opperson.sAge
     *
     * @mbggenerated
     */
    public Integer getSage() {
        return sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sAge
     *
     * @param sage the value for sa_opperson.sAge
     *
     * @mbggenerated
     */
    public void setSage(Integer sage) {
        this.sage = sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sClassification
     *
     * @return the value of sa_opperson.sClassification
     *
     * @mbggenerated
     */
    public String getSclassification() {
        return sclassification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sClassification
     *
     * @param sclassification the value for sa_opperson.sClassification
     *
     * @mbggenerated
     */
    public void setSclassification(String sclassification) {
        this.sclassification = sclassification == null ? null : sclassification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sState
     *
     * @return the value of sa_opperson.sState
     *
     * @mbggenerated
     */
    public String getSstate() {
        return sstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sState
     *
     * @param sstate the value for sa_opperson.sState
     *
     * @mbggenerated
     */
    public void setSstate(String sstate) {
        this.sstate = sstate == null ? null : sstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sWorkLife
     *
     * @return the value of sa_opperson.sWorkLife
     *
     * @mbggenerated
     */
    public Integer getSworklife() {
        return sworklife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sWorkLife
     *
     * @param sworklife the value for sa_opperson.sWorkLife
     *
     * @mbggenerated
     */
    public void setSworklife(Integer sworklife) {
        this.sworklife = sworklife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sLearnExperience
     *
     * @return the value of sa_opperson.sLearnExperience
     *
     * @mbggenerated
     */
    public String getSlearnexperience() {
        return slearnexperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sLearnExperience
     *
     * @param slearnexperience the value for sa_opperson.sLearnExperience
     *
     * @mbggenerated
     */
    public void setSlearnexperience(String slearnexperience) {
        this.slearnexperience = slearnexperience == null ? null : slearnexperience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sWorkExperience
     *
     * @return the value of sa_opperson.sWorkExperience
     *
     * @mbggenerated
     */
    public String getSworkexperience() {
        return sworkexperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sWorkExperience
     *
     * @param sworkexperience the value for sa_opperson.sWorkExperience
     *
     * @mbggenerated
     */
    public void setSworkexperience(String sworkexperience) {
        this.sworkexperience = sworkexperience == null ? null : sworkexperience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sTrainExperience
     *
     * @return the value of sa_opperson.sTrainExperience
     *
     * @mbggenerated
     */
    public String getStrainexperience() {
        return strainexperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sTrainExperience
     *
     * @param strainexperience the value for sa_opperson.sTrainExperience
     *
     * @mbggenerated
     */
    public void setStrainexperience(String strainexperience) {
        this.strainexperience = strainexperience == null ? null : strainexperience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sCertificate
     *
     * @return the value of sa_opperson.sCertificate
     *
     * @mbggenerated
     */
    public String getScertificate() {
        return scertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sCertificate
     *
     * @param scertificate the value for sa_opperson.sCertificate
     *
     * @mbggenerated
     */
    public void setScertificate(String scertificate) {
        this.scertificate = scertificate == null ? null : scertificate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sSafeLevelName
     *
     * @return the value of sa_opperson.sSafeLevelName
     *
     * @mbggenerated
     */
    public String getSsafelevelname() {
        return ssafelevelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sSafeLevelName
     *
     * @param ssafelevelname the value for sa_opperson.sSafeLevelName
     *
     * @mbggenerated
     */
    public void setSsafelevelname(String ssafelevelname) {
        this.ssafelevelname = ssafelevelname == null ? null : ssafelevelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sSexNo
     *
     * @return the value of sa_opperson.sSexNo
     *
     * @mbggenerated
     */
    public String getSsexno() {
        return ssexno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sSexNo
     *
     * @param ssexno the value for sa_opperson.sSexNo
     *
     * @mbggenerated
     */
    public void setSsexno(String ssexno) {
        this.ssexno = ssexno == null ? null : ssexno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sStateNO
     *
     * @return the value of sa_opperson.sStateNO
     *
     * @mbggenerated
     */
    public String getSstateno() {
        return sstateno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sStateNO
     *
     * @param sstateno the value for sa_opperson.sStateNO
     *
     * @mbggenerated
     */
    public void setSstateno(String sstateno) {
        this.sstateno = sstateno == null ? null : sstateno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.sPhoto
     *
     * @return the value of sa_opperson.sPhoto
     *
     * @mbggenerated
     */
    public byte[] getSphoto() {
        return sphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.sPhoto
     *
     * @param sphoto the value for sa_opperson.sPhoto
     *
     * @mbggenerated
     */
    public void setSphoto(byte[] sphoto) {
        this.sphoto = sphoto;
    }
}